cargo-features = ["test-dummy-unstable"]

[package]
name = "toqst-typer"
version = "0.1.0"
authors = ["BozeBro <ben.ozua@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
